### ISSUE TITLE
github actions that don't break..

### ISSUE THREAD

**Issue by tijeco** [tijeco/berteome#21]
So I'd like the actions environment to be the same as what is specified in some sort of conda environment file.

I'm looking at this here (https://github.com/marketplace/actions/setup-conda), I think I can use that to activate some sort of conda environment??

They have a nice set up for matrix testing which let's test run on multiple versions, I don't necessarily have any desire to really do that since it's a bit overkill.. but I figured I'd put it here for future reference.
```yaml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.8]
    name: Python ${{ matrix.python-version }} example
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
 ```
